### PR TITLE
Added the BB84 protocol definition.

### PR DESCRIPTION
**Pull request by BassemSafieldeen**
Hi Rich, 

I have added a draft of the BB84 protocol definition. Please merge it with your fork if you think it looks fine.

### CODE REVIEW

**Comment by richwheels** [comment]
Ps I don’t know who controls the PR system or completes the PRs once happy 😊

**Comment by BassemSafieldeen** [comment]
Hey Rich,

You still need to merge my pull request, I think.

**Comment by BassemSafieldeen** [comment]
Cool. Now please submit another pull request to the main repository (the one on qtm3x).

**Comment by richwheels** [comment]
Hopefully should have just done that. Let me know if any problems :)

**Comment by BassemSafieldeen** [comment]
Merged into main repo now (Y).

**Pull request merged**
